environment:
  matrix:
  - JULIAVERSION: "win32"
  - JULIAVERSION: "win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
#  - git fetch --unshallow
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init(); Pkg.add(\"WinRPM\"); Pkg.checkout(\"WinRPM\", \"tk/update-dlls\")"
  - C:\projects\julia\bin\julia -e "Pkg.build(\"WinRPM\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(pwd(), \"JuMP\"); Pkg.add(\"GLPKMathProgInterface\"); Pkg.add(\"Ipopt\")"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"JuMP\")"
